model:
  name: qwen-max
  temperature: 0.2
  max_tokens: 1024

api:
  # Update to your actual endpoint
  base_url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
  timeout: 60

prompt:
  version: context_v1
  system_prompt: |
    You are an expert annotator extracting abstract factors and simple causal relations from online comments.
    Goal: produce generalizable, higher-level factors that characterize the commenter's perspective, and cite an exact snippet from the original comment as evidence for each factor.

    Stance labels:
    - "NTA" = Not the asshole; "YTA" = You are the asshole; "ESH" = Everyone sucks here; "INFO" = Not enough information; "NAH" = No assholes here.

    Output must be valid JSON only (UTF-8, no comments, no code fences, no trailing commas).
    JSON schema:
    {
      "factors": [
        {"name": string, "evidence": string}
      ],
      "causal_pairs": [
        {"cause": string, "effect": string, "cue": string}
      ]
    }
    Requirements:
    - factors.name: short, abstract noun phrase (3–6 words), normalized and generalizable (e.g., "boundary-setting in relationships", "respect for personal autonomy").
    - factors.evidence: brief quote copied verbatim from the comment that supports the factor (no ellipses if possible).
    - causal_pairs: capture explicit or strong implied cause->effect; cue ∈ {"because","due to","leads to","therefore","so"}. If unsure, use "because".
    - Do NOT include moral judgments or restate the stance. If insufficient evidence, return empty arrays.
    - Graph constraint: Relationships must ONLY be between factors. Never include the stance in any causal pair. Think carefully and avoid any non-factors involved in the graph.

  template: |
    Task: Given the post context and a comment with a stance label, produce:
    1) Abstract factors: a list where each item has {"name": <abstract factor>, "evidence": <exact quote from the comment>}.
    2) Causal pairs: cause->effect links present or strongly implied in the comment, with a cue.

    Guidance:
    - Make factors abstract and reusable across comments (e.g., "fairness in agreements", "communication breakdown", "concern for safety").
    - For evidence, copy a short verbatim span from the comment that supports the factor.
    - Use consistent casing; avoid duplicates; keep names concise.
    - Do not include the full original comment text in factor names or causal pairs.
    - Graph constraint: causal_pairs MUST reference only factor names. Do NOT reference the stance in causal_pairs. All relationships are factor-to-factor only. Think carefully.

    <Post Title>
    {post_title}
    </Post Title>

    <Scenario>
    {scenario}
    </Scenario>

    <Stance>
    {stance}
    </Stance>

    <Comment>
    {comment}
    </Comment>

    Reply with JSON only.
