```mermaid
flowchart TD
    n1[Housing, Development, and Community in San Francisco]
    n3[Being an army brat]
    n9[Community Well-being and Financial Stability]
    n11[Riots in Oakland in 1967]
    n15[Discriminatory Housing Practices]
    n33[Real Estate Investments]
    n40[Education Investment and Quality]
    n42[Retention of students in public education]
    n45[Commodification of public spaces]
    n47[Developers maximizing profit]
    n55[providing housing at a decent rate]
    n62[Fillmore district]
    n73[mindset]
    n75[rich people in low-density areas]
    n101[Billion dollars a year]
    n103[Regional Planning for Housing]
    n104[Availability of services]
    n106[Residential distribution]
    n107[policies]
    n108[Housing Affordability]
    n109[building more houses]
    n111[existing policies]
    n112[Housing Development Policies]
    n113[starting a new game]
    n115[density of six units per lot in every neighborhood]
    n116[housing development policies]
    n1 --> n9
    n1 --x n33
    n1 --> n42
    n1 --x n62
    n3 --> n1
    n9 --x n1
    n11 --x n1
    n15 --x n1
    n33 --x n1
    n33 --> n9
    n45 --x n1
    n45 --x n9
    n47 --> n9
    n55 --> n1
    n73 --> n1
    n75 --x n1
    n101 --x n9
    n103 --> n104
    n103 --> n106
    n107 --x n108
    n109 --x n108
    n111 --> n112
    n113 --> n112
    n115 --> n116
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 4 stroke:#00AA00,stroke-width:2px
    linkStyle 5 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 6 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 7 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 8 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 9 stroke:#00AA00,stroke-width:2px
    linkStyle 10 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 11 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 12 stroke:#00AA00,stroke-width:2px
    linkStyle 13 stroke:#00AA00,stroke-width:2px
    linkStyle 14 stroke:#00AA00,stroke-width:2px
    linkStyle 15 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 16 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 17 stroke:#00AA00,stroke-width:2px
    linkStyle 18 stroke:#00AA00,stroke-width:2px
    linkStyle 19 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 20 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 21 stroke:#00AA00,stroke-width:2px
    linkStyle 22 stroke:#00AA00,stroke-width:2px
    linkStyle 23 stroke:#00AA00,stroke-width:2px
```