```mermaid
flowchart TD
    n1[Occupation and Income in San Francisco]
    n3[Being an army brat]
    n5[Housing and Property Ownership]
    n9[Financial Support/Stability]
    n11[Riots in Oakland in 1967]
    n13[Rich Community and Housing Development]
    n15[Discriminatory Housing Practices]
    n27[Urban Development and City Planning]
    n33[Real Estate Investments]
    n40[Education Investment and Quality]
    n41[Accessibility of museums and enrichments]
    n42[Retention of students in public education]
    n44[Accessibility of cultural institutions (e.g., museums, Academy of Sciences)]
    n45[Commodification of public spaces]
    n46[Budget allocation for public services]
    n47[Developers maximizing profit]
    n48[Inequitable distribution]
    n53[adversarial nature of landlord and tenant relationships]
    n55[providing housing at a decent rate]
    n57[offering special tax breaks]
    n60[Community Cohesion in Neighborhoods]
    n62[Fillmore district]
    n64[Property prices in lower Pacific Heights]
    n67[Presence of Families in the City]
    n68[Affordability of living]
    n70[Community well-being]
    n71[City's Focus on Prosperity and Workers]
    n73[mindset]
    n74[housing and development]
    n75[rich people in low-density areas]
    n77[politicians]
    n78[housing development]
    n79[development in old neighborhoods]
    n80[Angelo Wilson's feelings]
    n81[rich people or people in low-density areas]
    n83[Trust in People for Jobs and Raising Kids]
    n84[Decent Neighborhoods]
    n86[butcher their neighborhoods]
    n1 --> n5
    n3 --> n1
    n5 --> n1
    n5 --> n9
    n5 --x n33
    n9 --> n5
    n11 --x n5
    n15 --x n5
    n27 --x n5
    n27 --x n1
    n27 --x n60
    n27 --x n62
    n27 --> n64
    n33 --x n5
    n33 --> n48
    n41 --> n42
    n45 --x n44
    n45 --x n46
    n47 --> n48
    n53 --x n5
    n55 --> n5
    n57 --> n5
    n67 --> n68
    n67 --> n70
    n73 --> n74
    n75 --x n13
    n77 --x n78
    n79 --> n80
    n81 --> n83
    n83 --> n84
    n84 --x n86
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#00AA00,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#00AA00,stroke-width:2px
    linkStyle 4 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 5 stroke:#00AA00,stroke-width:2px
    linkStyle 6 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 7 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 8 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 9 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 10 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 11 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 12 stroke:#00AA00,stroke-width:2px
    linkStyle 13 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 14 stroke:#00AA00,stroke-width:2px
    linkStyle 15 stroke:#00AA00,stroke-width:2px
    linkStyle 16 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 17 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 18 stroke:#00AA00,stroke-width:2px
    linkStyle 19 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 20 stroke:#00AA00,stroke-width:2px
    linkStyle 21 stroke:#00AA00,stroke-width:2px
    linkStyle 22 stroke:#00AA00,stroke-width:2px
    linkStyle 23 stroke:#00AA00,stroke-width:2px
    linkStyle 24 stroke:#00AA00,stroke-width:2px
    linkStyle 25 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 26 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 27 stroke:#00AA00,stroke-width:2px
    linkStyle 28 stroke:#00AA00,stroke-width:2px
    linkStyle 29 stroke:#00AA00,stroke-width:2px
    linkStyle 30 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
```