```mermaid
flowchart TD
    n1[Occupation and Income in San Francisco]
    n3[Being an army brat]
    n5[San Francisco Housing]
    n9[Financial Support/Stability]
    n10[Property Ownership and Housing Costs]
    n11[Riots in Oakland in 1967]
    n13[Rich Community in San Francisco]
    n15[Discriminatory Housing Practices]
    n27[Urban Development]
    n32[Housing Policies]
    n33[Real Estate Investments]
    n35[Housing]
    n39[Investment in school system]
    n40[Quality of education]
    n41[Accessibility of museums and enrichments]
    n42[Retention of students in public education]
    n44[Accessibility of cultural institutions (e.g., museums, Academy of Sciences)]
    n45[Commodification of public spaces]
    n46[Budget allocation for public services]
    n47[Developers maximizing profit]
    n48[Inequitable distribution]
    n49[Housing seen as investment]
    n1 --> n10
    n1 --> n32
    n3 --> n1
    n5 --> n1
    n9 --> n10
    n10 --> n9
    n11 --x n5
    n15 --x n10
    n27 --x n5
    n27 --x n1
    n33 --x n32
    n35 --x n33
    n39 --> n40
    n41 --> n42
    n45 --x n44
    n45 --x n46
    n47 --> n48
    n49 --> n48
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#00AA00,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#00AA00,stroke-width:2px
    linkStyle 4 stroke:#00AA00,stroke-width:2px
    linkStyle 5 stroke:#00AA00,stroke-width:2px
    linkStyle 6 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 7 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 8 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 9 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 10 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 11 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 12 stroke:#00AA00,stroke-width:2px
    linkStyle 13 stroke:#00AA00,stroke-width:2px
    linkStyle 14 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 15 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 16 stroke:#00AA00,stroke-width:2px
    linkStyle 17 stroke:#00AA00,stroke-width:2px
```