```mermaid
flowchart TD
    n1[Occupation, Income, Housing, and Development in San Francisco]
    n3[Being an army brat]
    n5[Housing and Property Ownership in San Francisco]
    n9[Financial Stability, Community Well-being, and Care for Poor People]
    n11[Riots in Oakland in 1967]
    n15[Discriminatory Housing Practices]
    n27[Urban Development, Community Focus, and Public Services in San Francisco]
    n33[Real Estate Investments]
    n40[Education Investment and Quality]
    n42[Retention of students in public education]
    n45[Commodification of public spaces]
    n47[Developers maximizing profit]
    n48[Inequitable distribution]
    n55[providing housing at a decent rate]
    n62[Fillmore district]
    n73[mindset]
    n75[rich people in low-density areas]
    n99[Non-profit racket]
    n101[Billion dollars a year]
    n1 --> n5
    n1 --x n27
    n3 --> n1
    n5 --> n1
    n5 --> n9
    n5 --x n33
    n9 --> n5
    n9 --x n27
    n11 --x n5
    n15 --x n5
    n27 --> n5
    n27 --x n1
    n27 --> n42
    n27 --x n62
    n27 --> n9
    n33 --x n5
    n33 --> n48
    n45 --x n27
    n45 --x n9
    n47 --> n48
    n55 --> n5
    n73 --> n1
    n75 --x n5
    n99 --x n9
    n101 --x n9
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#00AA00,stroke-width:2px
    linkStyle 4 stroke:#00AA00,stroke-width:2px
    linkStyle 5 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 6 stroke:#00AA00,stroke-width:2px
    linkStyle 7 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 8 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 9 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 10 stroke:#00AA00,stroke-width:2px
    linkStyle 11 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 12 stroke:#00AA00,stroke-width:2px
    linkStyle 13 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 14 stroke:#00AA00,stroke-width:2px
    linkStyle 15 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 16 stroke:#00AA00,stroke-width:2px
    linkStyle 17 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 18 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 19 stroke:#00AA00,stroke-width:2px
    linkStyle 20 stroke:#00AA00,stroke-width:2px
    linkStyle 21 stroke:#00AA00,stroke-width:2px
    linkStyle 22 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 23 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 24 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
```