```mermaid
flowchart TD
    n1[Occupation/Retirement]
    n3[Being an army brat]
    n5[Moving to San Francisco in 1964]
    n4[Place of birth]
    n6[Residence]
    n8[Moving to the Presidio in the Waring housing area]
    n3 --> n4
    n5 --> n6
    n6 --> n8
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#00AA00,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
```