```mermaid
flowchart TD
    n1[Occupation and Income in San Francisco]
    n3[Being an army brat]
    n5[San Francisco Housing]
    n9[Financial Support/Stability]
    n10[Property Ownership and Housing Costs]
    n11[Riots in Oakland in 1967]
    n13[Rich Community in San Francisco]
    n15[Discriminatory Housing Practices]
    n23[Affordability of housing in San Francisco in the past]
    n27[Urban Development]
    n28[Housing market affordability]
    n32[Housing Policies]
    n33[Real Estate Investments]
    n35[housing]
    n36[Types of Housing]
    n1 --> n10
    n1 --> n32
    n3 --> n1
    n5 --> n1
    n9 --> n10
    n10 --> n9
    n11 --x n5
    n15 --x n10
    n23 --> n5
    n27 --x n28
    n27 --x n1
    n33 --x n32
    n35 --> n36
    n36 --x n33
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#00AA00,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#00AA00,stroke-width:2px
    linkStyle 4 stroke:#00AA00,stroke-width:2px
    linkStyle 5 stroke:#00AA00,stroke-width:2px
    linkStyle 6 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 7 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 8 stroke:#00AA00,stroke-width:2px
    linkStyle 9 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 10 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 11 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 12 stroke:#00AA00,stroke-width:2px
    linkStyle 13 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
```