```mermaid
flowchart TD
    n3[Being an army brat]
    n5[Moving to San Francisco in 1964]
    n9[stipend from the military]
    n11[Riots in Oakland in 1967]
    n13[Rich hippie area]
    n1[Occupation/Residence]
    n10[cost of housing in Waring housing area]
    n12[Family's decision to move back to San Francisco]
    n14[Famous neighbors]
    n4[Place of Birth/Residence]
    n1 --> n4
    n3 --> n4
    n5 --> n1
    n9 --> n10
    n11 --x n12
    n13 --> n14
    linkStyle 0 stroke:#00AA00,stroke-width:2px
    linkStyle 1 stroke:#00AA00,stroke-width:2px
    linkStyle 2 stroke:#00AA00,stroke-width:2px
    linkStyle 3 stroke:#00AA00,stroke-width:2px
    linkStyle 4 stroke:#FF0000,stroke-dasharray:3,stroke-width:2px
    linkStyle 5 stroke:#00AA00,stroke-width:2px
```